name: CI Test

on: [push]

jobs:
  prepare:
    runs-on: windows-latest

    steps:
      - name: Print SHA
        shell: cmd
        run: |
          echo %GITHUB_SHA%

      - name: Print REF
        shell: cmd
        run: |
          echo %GITHUB_REF%

  flake8-checks:
    runs-on: windows-latest

    needs: [prepare]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flake8
        run: |
          pip install flake8

      - name: flake8 - error check
        run: |
          flake8 . --config .flake8-error

      - name: flake8 - style check
        run: |
          flake8 . --config .flake8-style

  pylint-checks:
    runs-on: windows-latest

    needs: [prepare]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pylint
        run: |
          pip install pylint

  ci-tests:
    runs-on: windows-latest

    needs: [prepare]

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
